name: "Vowels (Automated Electrical Energy System)"
description: "A highly resilient, C#-based energy orchestrator (.NET Native AOT) that solves non-linear constraints and manages deferrable loads via a Resource API."
version: "0.1.0"
slug: "vowels"
init: false
image: "ghcr.io/thargy/{arch}-vowels"
arch:
  - aarch64
  - amd64
homeassistant_api: true
ingress: true
ingress_port: 5000
map:
  - homeassistant_config:rw
  - share:rw
options:
  entities: []
schema:
  entities:
    - str

